### ISSUE TITLE
Annotation for A_baumannii_AC12 [PGAP failed, docker exited with rc = 1]

### ISSUE THREAD

**Issue by wmml1234567890** [ncbi/pgap#162]
cwltool.log
[cwltool.log](https://github.com/ncbi/pgap/files/6928847/cwltool.log)

Input.yaml
```
fasta:
  class: File
  location: A_baumannii_AC12_CP007549_3.fna
submol:
  class: File
  location: submol.yaml
```

submol.yaml
```
organism:
    genus_species: 'Acinetobacter baumannii' 
```

Fasta
CP007549.3

Dear all,

We tried to use pgap to annotate the A. baumannii, but we get the above errors in the log file. The log file is attached above. Since the yaml and fna file is not supported, we just paste the information of these files here.

Thank you very much in advance.

Eddie
