### ISSUE TITLE
[BUG] WARNING [job fastaval] completed permanentFail

### ISSUE THREAD

**Issue by scrosson73** [ncbi/pgap#179]
**Describe the bug**
I am using build 5742, and am able to successfully run PGAP on the test genome MG37. However, my attempts to run PGAP on Brucella ovis chromosome 1 or B. ovis chomosome 2 end in an error. The failure seems to start with: (WARNING [job fastaval] completed permanentFail

**To Reproduce**
I am willing to share the genome.

**Expected behavior**
I expected PGAP to yield an annotated .gb file.

**Software versions (please complete the following information):**
 - OS: [MacOS v12.1]
 PGAP version 2021-11-29.build5742 is up to date.
 Docker version 20.10.11, build dea9396

**Log Files**

[logs.zip](https://github.com/ncbi/pgap/files/7818008/logs.zip)
[cwltool.log](https://github.com/ncbi/pgap/files/7818009/cwltool.log)

**Additional context**

**Comment by azat-badretdin** [comment]
Thank you for your report, Sean! Unfortunately, I am having trouble opening attached `logs.zip` file. Is it, perchance, gzipped instead of being zipped? 

At this moment we are actually interested in `submol.yaml` input file. Would you mind posting it? 

Thanks!

**Comment by scrosson73** [comment]
Thanks, Azat. I changed the extension to .txt so it would upload here. [submol.yaml.txt](https://github.com/ncbi/pgap/files/7822083/submol.yaml.txt)

**Comment by azat-badretdin** [comment]
This part: 
```
publications:
    - publication:
        pmid:
        title: 'Unpublished'
        status: published  # this is enum: controlled vocabulary
        authors:
            - author:
                first_name: 'UC'
                last_name: 'Pouchitis'

```

is unnecessary. As in our example, it is intended for describing existing publications. Could you please try it without this section?
