### ISSUE TITLE
[Errno 2] No such file or directory, but why?

### ISSUE THREAD

**Issue by AnmotCar** [ncbi/pgap#334]
Hello,

I am trying to make a script that will automatically populate the .yaml and submol.yaml files using the fasta file name. So I can run PGAP in bulk without having to interact with it.

My script seems to work and the files are generated correctly but then PGAP errors out and the only thing I can pick out from the log is that:
1. It says the fasta file isnt found, but it clearly found the file because it already started making the directory for it and copied it in. 
2.  The .yaml file is pointing to the submol.yaml (absolute path) yet in the log it looks like it generating a random one.

The final command out of the script for my little test file is 
~/bioinformatics/pgap.py --no-self-update --report-usage-false --no-internet -o Rhizobium_croatiense_barcode52 -c 10 -m 100g barcode52.pgap.yaml

I had to disable the update because I was getting syntax errors form the pgap.py script (found the solution in one of the closed threads on here)

barcode52.pgap.yaml looks like this and the submol file has the matching name.
```
fasta:
    class: File
    location: /media/oresnik/nanopore/5_Good_assemblies/Rhizobium_croatiense_barcode52.fasta
submol:
    class: File
    location: /media/oresnik/nanopore/6_PGAP_annotations/barcode52.pgap_submol.yaml
```
I attached the cwltool.log

[cwltool.log](https://github.com/user-attachments/files/18773031/cwltool.log)
