### ISSUE TITLE
[BUG] Failure during Prepare_Unannotated_Sequences_asnvalidate_evaluate step

### ISSUE THREAD

**Issue by ctSkennerton** [ncbi/pgap#51]
**Describe the bug**
PGAP fails at the Prepare_Unannotated_Sequences_asnvalidate_evaluate step with the error `<message severity="ERROR" seq-id="lcl|Contig_01" code="SEQ_DESCR_StrainWithEnvironSample">Strain should not be present in an environmental sample</message>`. 

**To Reproduce**
My input files look like the following, you can give it a different input fasta file to generate the same error. 
metadata.yaml
```
topology: 'linear'
locus_tag_prefix: 'AK208913'
organism:
    genus_species: 'Alistipes sp. CAG:29'
    strain: AK208913
contact_info:
    <...>
 ```
Note that the `genus_species` key is autogenerated by an upstream script, it is the best matching genome in NCBIs taxonomy.

input.yaml
```
report_usage: true
fasta:
    class: File
    location: /pgap/user_input/contigs_min1000.fasta
submol:
  class: File
  location: /pgap/user_input/metadata.yaml
```

**Software versions (please complete the following information):**
 - OS: ubuntu 18.04
 - pgap version 2019-11-25.build4172

**Log Files**
It's quite large and I can't attach it here.

**Additional context**
I suspect that because `Alistipes sp. CAG:29` is from an environmental sample PGAP is also assuming that my genome is from an environmental source and fails. My genome is not from an environmental sample though it's likely a new species of *Alistipes*, Alistipes sp. CAG:29 is mearly the closest relative based on sequence similarity.

What do you think the work around for this is? do I need to select an *Alistipes* species that isn't from an environmental source? can I just use the genus without the species since my genome is a new species of *Alistipes*?
